name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: my-step
        #run: echo "Hello World!"
        uses: actions/checkout@v2
      - run: ci/build-app.sh
      - name: Test
        run: ci/unit-test-app.sh
      - name: Upload Repo
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: .